rules:
  - key: Updated Site Settings
    type: TRACK
    description: Updated Site Settings
    version: 1
    labels: {}
    properties:
      legacy team id:
        type:
          - string
      ref:
        type:
          - string
      setting:
        type:
          - string
      settings_name:
        type:
          - string
      site id:
        type:
          - string
      site plan type:
        type:
          - string
      siteId: {}
      site_id:
        type:
          - string
      site_slug:
        type:
          - string
      source:
        type:
          - string
      team id: {}
      teamId: {}
      timestamp: {}
      wf session id:
        type:
          - string
      workspace id:
        type:
          - string
      workspace plan:
        type:
          - string
      workspace plan type:
        type:
          - string
      workspace role:
        type:
          - string
      workspace seat count:
        type:
          - integer
      workspace slug:
        type:
          - string
      workspace_id:
        type:
          - string
