rules:
  - key: Workspace Settings Page Viewed
    type: TRACK
    description: Workspace Settings Page Viewed
    version: 1
    labels: {}
    properties:
      page:
        type:
          - string
      ref:
        type:
          - string
      site id:
        type:
          - string
      site plan id:
        type:
          - string
      site plan type:
        type:
          - string
      site slug:
        type:
          - string
      source:
        type:
          - string
      workspace id:
        type:
          - string
      workspace is enterprise:
        type:
          - boolean
      workspace plan:
        type:
          - string
      workspace plan id:
        type:
          - string
      workspace plan type:
        type:
          - string
      workspace seat count:
        type:
          - integer
      workspace slug:
        type:
          - string
