rules:
  - key: Asset Settings Changed
    type: TRACK
    description: Asset Settings Changed
    version: 1
    labels: {}
    properties:
      action:
        type:
          - string
      active tutorials:
        type:
          - string
      alt text changed:
        type:
          - boolean
      alt text type changed:
        type:
          - boolean
      asset extension:
        type:
          - string
      asset id:
        type:
          - string
      asset type:
        type:
          - string
      cms item count:
        type:
          - integer
      designer workflow:
        type:
          - string
      ecommerce enabled:
        type:
          - boolean
      ecommerce item count:
        type:
          - integer
      folder changed:
        type:
          - boolean
      location:
        type:
          - string
      mode:
        type:
          - string
      name changed:
        type:
          - boolean
      page count:
        type:
          - integer
      page id:
        type:
          - string
      plan type:
        type:
          - string
      project item count:
        type:
          - integer
      site id:
        type:
          - string
      site published:
        type:
          - boolean
      site role:
        type:
          - string
      styles count:
        type:
          - integer
      total collection count:
        type:
          - integer
      tutorial: {}
      workspace id:
        type:
          - string
      workspace is enterprise:
        type:
          - boolean
      workspace plan:
        type:
          - string
      workspace seat count:
        type:
          - integer
      wxp enabled:
        type:
          - boolean
