name: Validate Yaml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ ** ]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate YAML files in tracking-rules for webflow and designer
        env:
          LINT_OPTIONS: '{extends: relaxed, rules: {line-length: {max: 120}}}'
        run: |
          yamllint -d "$LINT_OPTIONS" tracking-rules/webflow/.
          yamllint -d "$LINT_OPTIONS" tracking-rules/designer/.
